sudo: required

language: ruby

services:
  - docker

script:
  - docker-compose up -d
  - docker-compose ps
  - docker-compose logs
  - docker-compose inspect clair-scanner
  - docker exec -it clair-scanner singularity pull --name container.simg shub://vsoch/hello-world
  - docker exec -it clair-scanner sclair container.simg

