sudo: required

language: ruby

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - docker exec -it clair-scanner singularity pull --name container.simg shub://vsoch/hello-world
  - docker exec -it clair-scanner sclair container.simg

