clair-db:
  container_name: clair-db
  restart: always
  image: arminc/clair-db
  ports:
    - "5432:5432"

clair-scanner:
  container_name: clair-scanner
  privileged: true
  image: vanessa/stools-clair
  volumes:
    - .:/code
  ports:
    - "6060:6060"
    - "8080:8080"
  links:
    - clair-db:postgres
